{% extends parent_template %}

{% block scripts %}{{ super() }}
{{ package_name }} = "{{ package_name }}.manage:main",
{% endblock %}

{% block deps_tests %}{{ super() }}
    "pytest-djangoapp>=1.6.0",
{% endblock %}
